language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review_branches: # Add this section to specify branches for auto reviews
    - main
    - backend_module
    - fix/*
    - feat/*
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true