export const userCookie = {
  TOKEN: "token",
};

export const USER = {
  LOGIN: "LOGIN_AS_USER",
  LOGOUT: "LOGOUT_USER",
  UPDATE: "UPDATE_USER_INFO",
};

export const ALL_PROJECTS = {
  STORE: "STORE_PROJECT_DATA_IN_REDUCER",
  CHANGE_STATUS: "CHANGE_PROJECT_STATUS",
  ADD_NEW: "ADD_NEW_PROJECT",
  EDIT_DATA: "EDIT_PROJECT_DATA",
};
